export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCTS_FAIL = 'SET_PRODUCTS_FAIL';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const TOGGLE_CART = 'TOGGLE_CART'

export const TOGGLE_FILTER = 'TOGGLE_FILTER'

export const PURCHASE_INIT = 'PURCHASE_INIT'
export const PURCHASE_ORDER_START = 'PURCHASE_ORDER_START'
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS'
export const PURCHASE_ORDER_FAIL = 'PURCHASE_ORDER_FAIL'

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'
