export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCTS_START = 'SET_PRODUCTS_START';
export const SET_PRODUCTS_FAIL = 'SET_PRODUCTS_FAIL';

export const CART_INIT = 'CART_INIT'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const CART_CHECKOUT = 'CART_CHECKOUT'

export const TOGGLE_FILTER = 'TOGGLE_FILTER'

export const PURCHASE_INIT = 'PURCHASE_INIT'
export const PURCHASE_ORDER_START = 'PURCHASE_ORDER_START'
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS'
export const PURCHASE_ORDER_FAIL = 'PURCHASE_ORDER_FAIL'

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'

export const LOG_OUT = 'LOG_OUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'